export const grey = '#666666'
export const lightGrey = '#eee'
export const lightGreyHighlight = '#e5e5e5'
export const green = '#32ca93'
export const lightGreen = '#d4f5e9'
export const red = '#db3849'
export const lightRed = '#f8dade'
